"""adds provided_identity encrypted json column to fideopsdb

Revision ID: a92dee7840f4
Revises: fc90277bbcde
Create Date: 2022-07-08 11:16:40.817369

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "a92dee7840f4"
down_revision = "fc90277bbcde"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "privacyrequest",
        sa.Column(
            "provided_identity",
            sqlalchemy_utils.types.encrypted.encrypted_type.StringEncryptedType(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("privacyrequest", "provided_identity")
    # ### end Alembic commands ###
