services:
  mariadb_example:
    image: mariadb
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MARIADB_HOST=mariadb_example
      - MARIADB_DATABASE=mariadb_example
      - MARIADB_ROOT_PASSWORD=example
      - MARIADB_USER=mariadb_user
      - MARIADB_PASSWORD=mariadb_pw
    expose:
      - 3306
    ports:
      - "3306:3306"
    # Because we're using the "-f" flag from a parent directory, this relative path needs
    # to be from the parent directory as well
    volumes:
      - ./docker/sample_data/mariadb_example_schema.sql:/docker-entrypoint-initdb.d/mariadb_example_schema.sql

  mongodb_example:
    image: mongo:5.0.3
    environment:
      - MONGO_INITDB_DATABASE=mongo_test
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_pass
    expose:
      - 27017
    ports:
      - "27017:27017"
    # Because we're using the "-f" flag from a parent directory, this relative path needs
    # to be from the parent directory as well
    volumes:
      - ./docker/sample_data/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mssql_example:
    image: mcr.microsoft.com/azure-sql-edge:latest # Equivalent to SQL Server 2016
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=Mssql_pw1
      - ACCEPT_EULA="Y"

  mysql_example:
    image: mysql
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_HOST=mysql_example
      - MYSQL_DATABASE=mysql_example
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql_pw
    expose:
      - 3307
    ports:
      - "3307:3306"
    # Because we're using the "-f" flag from a parent directory, this relative path needs
    # to be from the parent directory as well
    volumes:
      - ./docker/sample_data/mysql_example.sql:/docker-entrypoint-initdb.d/mysql_example.sql

  postgres_example:
    command:
      [
        "postgres",
        "-c",
        "logging_collector=on",
        "-c",
        "log_statement=all",
        "-c",
        "log_destination=stderr"
      ]
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_example
    expose:
      - 6432
    ports:
      - "0.0.0.0:6432:5432"
