"""add single action policy

Revision ID: b2b5a92902b9
Revises: 5078badb90b9
Create Date: 2022-05-26 18:02:34.933454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b5a92902b9'
down_revision = '5078badb90b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy', sa.Column('is_single_action_type', sa.Boolean(), nullable=True, default=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy', 'is_single_action_type')
    # ### end Alembic commands ###
