"""make client_id optional

Revision ID: b2cf1d94f542
Revises: 1dfc5a2d30e7
Create Date: 2022-02-28 23:25:17.102609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cf1d94f542'
down_revision = '1dfc5a2d30e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
