services:
  mssql_example:
    image: mcr.microsoft.com/azure-sql-edge:latest # Equivalent to SQL Server 2016
    restart: unless-stopped
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=Mssql_pw1
      - ACCEPT_EULA="Y"
