name: Publish to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  publish_to_pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Twine
        run: pip install twine

      - name: Twine Upload
        run: |
          python setup.py sdist
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
